name: Java CI with Maven

on: workflow_dispatch
  #push:
   # branches: [ "master" ]
# pull_request:
    #branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Java Version
      run: |
        Java_Version=$(mvn help:evaluate "-Dexpression=maven.compiler.release" -q -DforceStdout | sed -e 's/^1\./1.0./')
        echo "Java_Version=$Java_Version" >> $GITHUB_ENV
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.Java_Version }}
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn -B compile --file pom.xml
    - name: RunTests
      run: mvn -B test --file pom.xml
      
