on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: BuildCode
      run: mvn -B compile -Dmaven.compiler.target=19 -Dmaven.compiler.source=19 --file pom.xml
    - name: RunTests
      run: mvn -B test --file pom.xml
