name: Java CI with Maven

on: workflow_dispatch
  #push:
   # branches: [ "master" ]
# pull_request:
    #branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Java Version
      run: echo ::set-env name=JAVA_VERSION::$(mvn help:evaluate "-Dexpression=maven.compiler.release" -q -DforceStdout)
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION}}
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn -B compile --file pom.xml
    - name: RunTests
      run: mvn -B test --file pom.xml
      
